services:
  influxdb:
    image: influxdb:2.7.5-alpine
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    volumes:
      - ${MOSQUITTO_CFG_PATH}:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883

  telegraf:
    image: telegraf:1.30.0-alpine
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
      - mosquitto

  device_simulation:
    image: device_simulation
    depends_on:
      - influxdb
      - mosquitto
      - telegraf

  client:
    image: client
    ports:
      - 80:80
    depends_on:
      - mosquitto
      - telegraf

  grafana:
    image: grafana/grafana-oss
    ports:
      - '3000:3000'
    depends_on:
      - influxdb
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning

volumes:
  influxdb-storage:
  grafana: {}
